- apt:
    name: postgresql
    state: present

- service:
    name: postgresql
    state: started
    enabled: true
    
- copy:
    src: postgresql.conf
    dest: /etc/postgresql/17/main/postgresql.conf
    owner: root
    group: root
    mode: "0644"
  notify: restart postgresql
